// Generated by gencpp from file aev_pkg/lane_detection_msg.msg
// DO NOT EDIT!


#ifndef AEV_PKG_MESSAGE_LANE_DETECTION_MSG_H
#define AEV_PKG_MESSAGE_LANE_DETECTION_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aev_pkg
{
template <class ContainerAllocator>
struct lane_detection_msg_
{
  typedef lane_detection_msg_<ContainerAllocator> Type;

  lane_detection_msg_()
    : msg_counter(0)
    , centerOffset(0.0)
    , curvature(0.0)  {
    }
  lane_detection_msg_(const ContainerAllocator& _alloc)
    : msg_counter(0)
    , centerOffset(0.0)
    , curvature(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _msg_counter_type;
  _msg_counter_type msg_counter;

   typedef float _centerOffset_type;
  _centerOffset_type centerOffset;

   typedef float _curvature_type;
  _curvature_type curvature;





  typedef boost::shared_ptr< ::aev_pkg::lane_detection_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aev_pkg::lane_detection_msg_<ContainerAllocator> const> ConstPtr;

}; // struct lane_detection_msg_

typedef ::aev_pkg::lane_detection_msg_<std::allocator<void> > lane_detection_msg;

typedef boost::shared_ptr< ::aev_pkg::lane_detection_msg > lane_detection_msgPtr;
typedef boost::shared_ptr< ::aev_pkg::lane_detection_msg const> lane_detection_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aev_pkg::lane_detection_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aev_pkg::lane_detection_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aev_pkg::lane_detection_msg_<ContainerAllocator1> & lhs, const ::aev_pkg::lane_detection_msg_<ContainerAllocator2> & rhs)
{
  return lhs.msg_counter == rhs.msg_counter &&
    lhs.centerOffset == rhs.centerOffset &&
    lhs.curvature == rhs.curvature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aev_pkg::lane_detection_msg_<ContainerAllocator1> & lhs, const ::aev_pkg::lane_detection_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aev_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::aev_pkg::lane_detection_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aev_pkg::lane_detection_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aev_pkg::lane_detection_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aev_pkg::lane_detection_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aev_pkg::lane_detection_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aev_pkg::lane_detection_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aev_pkg::lane_detection_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4d45354acbb17a17b0a237f7d810945c";
  }

  static const char* value(const ::aev_pkg::lane_detection_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4d45354acbb17a17ULL;
  static const uint64_t static_value2 = 0xb0a237f7d810945cULL;
};

template<class ContainerAllocator>
struct DataType< ::aev_pkg::lane_detection_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aev_pkg/lane_detection_msg";
  }

  static const char* value(const ::aev_pkg::lane_detection_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aev_pkg::lane_detection_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 	msg_counter\n"
"float32 centerOffset\n"
"float32 curvature\n"
;
  }

  static const char* value(const ::aev_pkg::lane_detection_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aev_pkg::lane_detection_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msg_counter);
      stream.next(m.centerOffset);
      stream.next(m.curvature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lane_detection_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aev_pkg::lane_detection_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aev_pkg::lane_detection_msg_<ContainerAllocator>& v)
  {
    s << indent << "msg_counter: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.msg_counter);
    s << indent << "centerOffset: ";
    Printer<float>::stream(s, indent + "  ", v.centerOffset);
    s << indent << "curvature: ";
    Printer<float>::stream(s, indent + "  ", v.curvature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AEV_PKG_MESSAGE_LANE_DETECTION_MSG_H
