// Generated by gencpp from file aev_pkg/obstruction_imu_mgs.msg
// DO NOT EDIT!


#ifndef AEV_PKG_MESSAGE_OBSTRUCTION_IMU_MGS_H
#define AEV_PKG_MESSAGE_OBSTRUCTION_IMU_MGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aev_pkg
{
template <class ContainerAllocator>
struct obstruction_imu_mgs_
{
  typedef obstruction_imu_mgs_<ContainerAllocator> Type;

  obstruction_imu_mgs_()
    : msg_counter(0)
    , obstruction(false)
    , yaw_rate(0.0)  {
    }
  obstruction_imu_mgs_(const ContainerAllocator& _alloc)
    : msg_counter(0)
    , obstruction(false)
    , yaw_rate(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _msg_counter_type;
  _msg_counter_type msg_counter;

   typedef uint8_t _obstruction_type;
  _obstruction_type obstruction;

   typedef double _yaw_rate_type;
  _yaw_rate_type yaw_rate;





  typedef boost::shared_ptr< ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator> const> ConstPtr;

}; // struct obstruction_imu_mgs_

typedef ::aev_pkg::obstruction_imu_mgs_<std::allocator<void> > obstruction_imu_mgs;

typedef boost::shared_ptr< ::aev_pkg::obstruction_imu_mgs > obstruction_imu_mgsPtr;
typedef boost::shared_ptr< ::aev_pkg::obstruction_imu_mgs const> obstruction_imu_mgsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator1> & lhs, const ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator2> & rhs)
{
  return lhs.msg_counter == rhs.msg_counter &&
    lhs.obstruction == rhs.obstruction &&
    lhs.yaw_rate == rhs.yaw_rate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator1> & lhs, const ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aev_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0d4c64278182e7c8fb2d6201af193e53";
  }

  static const char* value(const ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0d4c64278182e7c8ULL;
  static const uint64_t static_value2 = 0xfb2d6201af193e53ULL;
};

template<class ContainerAllocator>
struct DataType< ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aev_pkg/obstruction_imu_mgs";
  }

  static const char* value(const ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 	msg_counter\n"
"bool 	obstruction\n"
"float64 yaw_rate\n"
;
  }

  static const char* value(const ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msg_counter);
      stream.next(m.obstruction);
      stream.next(m.yaw_rate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct obstruction_imu_mgs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aev_pkg::obstruction_imu_mgs_<ContainerAllocator>& v)
  {
    s << indent << "msg_counter: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.msg_counter);
    s << indent << "obstruction: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.obstruction);
    s << indent << "yaw_rate: ";
    Printer<double>::stream(s, indent + "  ", v.yaw_rate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AEV_PKG_MESSAGE_OBSTRUCTION_IMU_MGS_H
