(cl:in-package aev_pkg-msg)
(cl:export '(MSG_COUNTER-VAL
          MSG_COUNTER
          FEEDBACKSPEED_B1-VAL
          FEEDBACKSPEED_B1
          FEEDBACKSPEED_B2-VAL
          FEEDBACKSPEED_B2
          FEEDBACKSPEED_B3-VAL
          FEEDBACKSPEED_B3
          FEEDBACKSPEED_B4-VAL
          FEEDBACKSPEED_B4
          ACCELERATORLEVEL-VAL
          ACCELERATORLEVEL
          ACCELERATORSWITCH-VAL
          ACCELERATORSWITCH
          BRAKESWITCH-VAL
          BRAKESWITCH
          MOVINGDIRECTION-VAL
          MOVINGDIRECTION
          TURNSIGNAL-VAL
          TURNSIGNAL
          HORN-VAL
          HORN
          FRONTLIGHT-VAL
          FRONTLIGHT
))