# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from aev_pkg/obstruction_imu_mgs.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class obstruction_imu_mgs(genpy.Message):
  _md5sum = "0d4c64278182e7c8fb2d6201af193e53"
  _type = "aev_pkg/obstruction_imu_mgs"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint32 	msg_counter
bool 	obstruction
float64 yaw_rate"""
  __slots__ = ['msg_counter','obstruction','yaw_rate']
  _slot_types = ['uint32','bool','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       msg_counter,obstruction,yaw_rate

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(obstruction_imu_mgs, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.msg_counter is None:
        self.msg_counter = 0
      if self.obstruction is None:
        self.obstruction = False
      if self.yaw_rate is None:
        self.yaw_rate = 0.
    else:
      self.msg_counter = 0
      self.obstruction = False
      self.yaw_rate = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_IBd().pack(_x.msg_counter, _x.obstruction, _x.yaw_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.msg_counter, _x.obstruction, _x.yaw_rate,) = _get_struct_IBd().unpack(str[start:end])
      self.obstruction = bool(self.obstruction)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_IBd().pack(_x.msg_counter, _x.obstruction, _x.yaw_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.msg_counter, _x.obstruction, _x.yaw_rate,) = _get_struct_IBd().unpack(str[start:end])
      self.obstruction = bool(self.obstruction)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_IBd = None
def _get_struct_IBd():
    global _struct_IBd
    if _struct_IBd is None:
        _struct_IBd = struct.Struct("<IBd")
    return _struct_IBd
