# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from aev_pkg/system_monitor_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class system_monitor_msg(genpy.Message):
  _md5sum = "7fae4553a12c1b5cf670af37bb199a65"
  _type = "aev_pkg/system_monitor_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool 	errorFlag
bool 	stopRequestFlag
uint32 	errorInfo
"""
  __slots__ = ['errorFlag','stopRequestFlag','errorInfo']
  _slot_types = ['bool','bool','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       errorFlag,stopRequestFlag,errorInfo

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(system_monitor_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.errorFlag is None:
        self.errorFlag = False
      if self.stopRequestFlag is None:
        self.stopRequestFlag = False
      if self.errorInfo is None:
        self.errorInfo = 0
    else:
      self.errorFlag = False
      self.stopRequestFlag = False
      self.errorInfo = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2BI().pack(_x.errorFlag, _x.stopRequestFlag, _x.errorInfo))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.errorFlag, _x.stopRequestFlag, _x.errorInfo,) = _get_struct_2BI().unpack(str[start:end])
      self.errorFlag = bool(self.errorFlag)
      self.stopRequestFlag = bool(self.stopRequestFlag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2BI().pack(_x.errorFlag, _x.stopRequestFlag, _x.errorInfo))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.errorFlag, _x.stopRequestFlag, _x.errorInfo,) = _get_struct_2BI().unpack(str[start:end])
      self.errorFlag = bool(self.errorFlag)
      self.stopRequestFlag = bool(self.stopRequestFlag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2BI = None
def _get_struct_2BI():
    global _struct_2BI
    if _struct_2BI is None:
        _struct_2BI = struct.Struct("<2BI")
    return _struct_2BI
